"""empty message

Revision ID: 4103e7483bc6
Revises: 27c3e82cf0e1
Create Date: 2019-03-14 01:53:06.105645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4103e7483bc6'
down_revision = '27c3e82cf0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_post', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('blog_post', 'text',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('blog_post', 'title',
               existing_type=mysql.VARCHAR(length=140),
               nullable=False)
    op.alter_column('blog_post', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'blog_post', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'profile_image',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'profile_image',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.alter_column('blog_post', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('blog_post', 'title',
               existing_type=mysql.VARCHAR(length=140),
               nullable=True)
    op.alter_column('blog_post', 'text',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('blog_post', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
